[package]
name = "iced-pallete"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = { version = "0.14.0", features = ["canvas"] }
iced_core = "0.14.0"
iced_graphics = { version = "0.14.0", features = ["geometry"] }
iced_widget = { version = "0.14.2", features = ["canvas"] }
